### ISSUE TITLE
Why have this repo if nobody is going to maintain it?

### ISSUE THREAD

**Issue by NeckBeardPrince** [smallstep/hello-mtls#95]

**Comment by dopey** [comment]
Hey @NeckBeardPrince 👋  thanks for opening the issue. 

We created this repo as a resource for ourselves and because we thought it might be useful to other folks who are searching for TLS or mTLS between various services. In my opinion, this repo is still serving that purpose.

Are there particular updates or documentation that you'd like added? Looking at the open issues, I don't see any that have been added recently. 

And lastly, this project is open source for a reason. We want to encourage participation and contributions from the community. Our team is small and we can't possibly monitor all the different technologies that we've documented for changes and updates. If you're experiencing an issue with a particular technology, please open an issue, OR, better yet, submit a PR. 

cheers 🍻
